### ISSUE TITLE
Customize UsersManagementController.php?

### ISSUE THREAD

**Issue by MACscr** [jeremykenedy/laravel-users#19]
Whats the proper way to customize the User Management Controller without editing it within the vendor directory? Since it has hardcoded user fields, I would think it would almost always need to be customized, but during registration/publishing, it doesnt seem to be copied to the projects directories like the config and resources files are.

**Comment by jeremykenedy** [comment]
You would need to fork it and make the edits you need if they are not what the package provides. thats the core of the package.

https://laravel.com/docs/5.6/packages
