### ISSUE TITLE
not install laravel 5.2.*

### ISSUE THREAD

**Issue by michelmelo** [jeremykenedy/laravel-users#2]
`composer require jeremykenedy/laravel-users      
Using version ^1.0 for jeremykenedy/laravel-users
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.2.45
    - Conclusion: don't install laravel/framework v5.2.45
    - jeremykenedy/laravel-users v1.0.0 requires laravelcollective/html ^5.3.0 -> satisfiable by laravelcollective/html[v5.3.0, v5.3.1, v5.4, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6].
    - jeremykenedy/laravel-users v1.0.1 requires laravelcollective/html ^5.3.0 -> satisfiable by laravelcollective/html[v5.3.0, v5.3.1, v5.4, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6].
    - laravelcollective/html v5.3.0 requires illuminate/view 5.3.* -> satisfiable by illuminate/view[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - laravelcollective/html v5.3.1 requires illuminate/view 5.3.* -> satisfiable by illuminate/view[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - laravelcollective/html v5.4 requires illuminate/view 5.4.* -> satisfiable by illuminate/view[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.9].
    - laravelcollective/html v5.4.1 requires illuminate/view 5.4.* -> satisfiable by illuminate/view[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.9].
    - laravelcollective/html v5.4.2 requires illuminate/view 5.4.* -> satisfiable by illuminate/view[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.9].
    - laravelcollective/html v5.4.3 requires illuminate/view 5.4.* -> satisfiable by illuminate/view[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.9].
    - laravelcollective/html v5.4.4 requires illuminate/view 5.4.* -> satisfiable by illuminate/view[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.9].
    - laravelcollective/html v5.4.5 requires illuminate/view 5.4.* -> satisfiable by illuminate/view[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.9].
    - laravelcollective/html v5.4.6 requires illuminate/view 5.4.* -> satisfiable by illuminate/view[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.9].
    - don't install illuminate/view v5.3.0|don't install laravel/framework v5.2.45
    - don't install illuminate/view v5.3.16|don't install laravel/framework v5.2.45
    - don't install illuminate/view v5.3.23|don't install laravel/framework v5.2.45
    - don't install illuminate/view v5.3.4|don't install laravel/framework v5.2.45
    - don't install illuminate/view v5.4.0|don't install laravel/framework v5.2.45
    - don't install illuminate/view v5.4.13|don't install laravel/framework v5.2.45
    - don't install illuminate/view v5.4.17|don't install laravel/framework v5.2.45
    - don't install illuminate/view v5.4.19|don't install laravel/framework v5.2.45
    - don't install illuminate/view v5.4.9|don't install laravel/framework v5.2.45
    - Installation request for laravel/framework (locked at v5.2.45, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.45].
    - Installation request for jeremykenedy/laravel-users ^1.0 -> satisfiable by jeremykenedy/laravel-users[v1.0.0, v1.0.1].

Installation failed, reverting ./composer.json to its original content.`

**Comment by jeremykenedy** [comment]
Hello, thank you for letting me know. This is caused by a conflict in the dependency `laravelcollective/html`.  

I have updated the repo to handle this.

If you use `composer require jeremykenedy/laravel-users:1.2.0` that will work on Laravel 5.2

Thanks,
