### ISSUE TITLE
Bug: System will not make use of published config

### ISSUE THREAD

**Issue by hirsty** [jeremykenedy/laravel-users#25]
**Steps to Reproduce**

1. Follow Installation instructions to install into an existing Laravel Project
2. Edit the published config to point main template to one that exists in your layouts folder (for this, i simply remove the "laravevelusers::" as I had an app.blade.php)
3. Npm run dev and clear view cache just in case

**Expected Result**

Your template to change to my template

**Actual Result**

Defaults to your own template, although our template is working fine everywhere else.

**Comment by hirsty** [comment]
Love it, no explanation just close an actual issue

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-users#opening-an-issue.

**Comment by alecvinent** [comment]
Hello. I've recently installl this addon and I'm getting the same bug, so default templates remains activated.

**Comment by jeremykenedy** [comment]
Neither one of you read the link above before opening an issue. I just don’t have time for people who cannot respect that.
