### ISSUE TITLE
Invalid translations - html entities

### ISSUE THREAD

**Issue by xorock** [jeremykenedy/laravel-users#26]
Hello.
I did clean install of LV 5.6 + this package. Unfortunately all icons are displayed as html entities not as parsed HTML which is default behaviour of blade templates. Could You fix it?

**Comment by jeremykenedy** [comment]
Hello, 
Thank you for using the package.
I am unable to replicate the issue. Can you please provide a screenshot and steps you took. 
Thank you.

**Comment by xorock** [comment]
![lv](https://user-images.githubusercontent.com/111481/45053777-4dfa6b80-b08b-11e8-9838-74069f5cc154.png)

![lv2](https://user-images.githubusercontent.com/111481/45054115-530bea80-b08c-11e8-920a-d6632e051ff3.png)


It was standard installation. composer.json:

```
"require": {
        "php": "^7.1.3",
        "barryvdh/laravel-ide-helper": "^2.5",
        "fideloper/proxy": "^4.0",
        "jeremykenedy/laravel-users": "^3.1",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
```

```
composer create-project --prefer-dist laravel/laravel blog "5.6.*" 
composer require jeremykenedy/laravel-users
php artisan make:auth
php artisan vendor:publish --tag=laravelusers
php artisan migrate
```

**Comment by jeremykenedy** [comment]
It's something with using `@lang` which equivalates to using `{{ }}`, as soon as time allows I will test with replacing the `@lang` with `{!! !!}` syntax to see if that may fix it.

**Comment by jeremykenedy** [comment]
This commit https://github.com/jeremykenedy/laravel-users/commit/c6af076bd5584119b386300bbd1c4ba81fbf6b8f has solved this. Thanks!
