### ISSUE TITLE
Logout dropdown not showing

### ISSUE THREAD

**Issue by float1** [jeremykenedy/laravel-users#27]
Hello,
    can you help me with this problem, in defalut Laravel app.blade.php Logout shows but when i go to /users then laravel-users app.blade.php loads and there from I can't get Logout to show.
Laravel version is latest i gues installer and created project with composer.

If it is stupid question just delete it. Thank you.

Edit: it has something to do with enableAppJs => false, but i don't understand if this is ok to do

**Comment by Mapteg34** [comment]
Check you blade templates. Default views of this package use bootstrap, and if you already use it on you templates - bootstrap loading 2 times, and fail

**Comment by jeremykenedy** [comment]
Is this still an issue?

**Comment by jeremykenedy** [comment]
I am going to close the issue and if it comes up again let me know.

Thanks,

**Comment by marcelozarate** [comment]
I solved this issue by modifying the file

> config/laravelusers.php

`'enableBootstrapJsCdn'          => true,`

with:

`'enableBootstrapJsCdn'          => false,`
