### ISSUE TITLE
Argument 3 passed to NetoJose\Bootstrap4Forms\FormService::text() must be of the type string or null, array given,  RROR) Argument 3 passed to NetoJose\Bootstrap4Forms\FormService::text() must be of the type string or null, array given,  vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php

### ISSUE THREAD

**Issue by mbelatar** [jeremykenedy/laravel-users#29]
ErrorException (E_ERROR)
Argument 3 passed to NetoJose\Bootstrap4Forms\FormService::text() must be of the type string or null, array given, called in C:\server\www\projects\new\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 223 (View: C:\server\www\projects\new\vendor\jeremykenedy\laravel-users\src\resources\views\usersmanagement\create-user.blade.php)
Previous exceptions
Argument 3 passed to NetoJose\Bootstrap4Forms\FormService::text() must be of the type string or null, array given, called in C:\server\www\projects\new\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 223 (0)

**Comment by jeremykenedy** [comment]
I can not replicate this.

**Comment by mbelatar** [comment]
i did not understand you bro

**Comment by mbelatar** [comment]
this is what happen just after install

**Comment by jeremykenedy** [comment]
This ‘NetoJose\Bootstrap4Forms\FormService::text()‘ is not part of this package. I cannot replicate this issue.

Can you provide more information on your implementation and possibly your user model.
