### ISSUE TITLE
How to integrate this package in GUI

### ISSUE THREAD

**Issue by amarathota** [jeremykenedy/laravel-users#30]
Hi, 

I have installed this package but it showing a different UI or layout. Could you please let me know how to integrate into my existing layout. Thanks!

**Comment by jeremykenedy** [comment]
After you publish the config you change the view you are extending from in that file.

It’s the first setting in the config file.

This project has it extended off the admin layout which is a different view as you described above:

https://github.com/jeremykenedy/larablog
