### ISSUE TITLE
Delete a user modal message wrong

### ISSUE THREAD

**Issue by kamov** [jeremykenedy/laravel-users#31]
When I try to delete a user, the message in modal box is like:

Are you sure you want to delete '+val.name+'?

**Comment by kamov** [comment]
The html source code show this:

![screenshot from 2018-12-14 15-46-15](https://user-images.githubusercontent.com/2345000/50009486-6a297500-ffb7-11e8-8fd0-534a2a04f768.png)

**Comment by jeremykenedy** [comment]
I cannot replicate this  issue. Your app may have some javascript conflicts.

**Comment by jeremykenedy** [comment]
Check the console to see the conflicts.
