### ISSUE TITLE
Dropdown of user not work

### ISSUE THREAD

**Issue by kamov** [jeremykenedy/laravel-users#32]
I can't open top right dropdown in header, this:

![screenshot from 2018-12-14 15-47-59](https://user-images.githubusercontent.com/2345000/50009647-c391a400-ffb7-11e8-9027-bc8ebcd9d365.png)

**Comment by jeremykenedy** [comment]
You need to resolve javascript conflicts within your app.

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-users/issues/27
