### ISSUE TITLE
Enable datatables

### ISSUE THREAD

**Issue by kamov** [jeremykenedy/laravel-users#33]
Via config I enable datatables but nothing change, this : 
'enabledDatatablesJs'           => true,

**Comment by jeremykenedy** [comment]
You need to resolve javascript conflicts within your app.

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-users/issues/27

**Comment by kamov** [comment]
I will reply here for all other tickets since the issue you said is js conflict.
In the console I don't see anything, that was the first place where I check.

I just install laravel and your package, nothing else.
So I suppose that it should work without changing anything, no?

See here the content of my html page:
https://pastebin.com/0nrH0Snc

To me seem all correctly loaded.

Please let me know if you see what is missing.

**Comment by jeremykenedy** [comment]
Is this still an issue?
