### ISSUE TITLE
Not installing fully

### ISSUE THREAD

**Issue by GazEdBro** [jeremykenedy/laravel-users#35]
I have just started a new Laravel project and want to use laravel-users for user management.  However on an install (PHP 7.1, Laravel 5.7 and the current version of this code) both I and a colleague, separately, are getting the error "Route [login] not defined." when browsing to /users.  Looking at the result of the install it seems that neither providers nor aliases have been updated, and the migrations did not seem to run, despite package discovery locating correctly and no faults displayed in the console.  Any ideas would be appreciated, thank you.

**Comment by jeremykenedy** [comment]
Are you using laravel standard authentication? That’s what’s missing. That is part of the core of laravel not this package.

**Comment by GazEdBro** [comment]
That was it, thank you very much!

**Comment by kaeland** [comment]
I ran into the same issue. It may be helpful to place the solution in the README... for those who are new to Laravel like me. 😊
