### ISSUE TITLE
I don't know how to install

### ISSUE THREAD

**Issue by measproem** [jeremykenedy/laravel-users#36]
Hi,

I followed : composer require jeremykenedy/laravel-users via CMD on window then got download "vendor" folder I don't know how to do next.

**Comment by jeremykenedy** [comment]
Did you read the readme?

**Comment by measproem** [comment]
I read but seem not clear understand.

**Comment by jeremykenedy** [comment]
What don’t you understand?

**Comment by measproem** [comment]
> 
> 
> What don’t you understand?

![1](https://user-images.githubusercontent.com/12493849/54658124-909f0500-4afe-11e9-8274-c3c1ddeb654f.JPG)
![2](https://user-images.githubusercontent.com/12493849/54658125-909f0500-4afe-11e9-8c2c-d0c69faa7d97.JPG)
![3](https://user-images.githubusercontent.com/12493849/54658126-909f0500-4afe-11e9-8736-e09f400066cc.JPG)
I created vhost name: http://laravel-usermng.local by point to parth project/public I got like screen #2
Then I access http://laravel-usermng.local/users  I got 404 page not found like screen #3

**Comment by jeremykenedy** [comment]
What environment are you using, have you tested other routes such at Auth routes?

**Comment by measproem** [comment]
> 
> 
> What environment are you using, have you tested other routes such at Auth routes?

 I am using Window and XAMPP.
I check project/routes/web.php
I got like screen below
![image](https://user-images.githubusercontent.com/12493849/54659118-2a68b100-4b03-11e9-9c31-d7a7b0d509c8.png)

**Comment by jeremykenedy** [comment]
It could me the environment you are on not serving past the root page. I can not replicate the issue using homestead.

**Comment by jeremykenedy** [comment]
Can you access the out box authentication routes? After running ‘php artisan make:auth’ ?

If not, then it’s your environment.

https://stackoverflow.com/questions/44371009/xampp-localhost-not-working

**Comment by measproem** [comment]
> 
> 
> Can you access the out box authentication routes? After running ‘php artisan make:auth’ ?
> 
> If not, then it’s your environment.
> 
> https://stackoverflow.com/questions/44371009/xampp-localhost-not-working

I did make:auth not work too, my idea not because environment 
I afraid I am wrong during installation process let me tell you the step:

1. CMD to my project parth: E:/xampp/htdocs/laravel-usermng.local (where i point vhost : http://laravel-usermng.local)
2. I install Laravel installer by run command : composer global require laravel/installer
3. I install your project 'laravel-users' by run command:  composer require jeremykenedy/laravel-users
4. I make new project on root by run command: laravel new
5. I run command : php migrate  for create table and make auth ..
