### ISSUE TITLE
Support language Portuguese Brazil (Files)

### ISSUE THREAD

**Issue by nibri10** [jeremykenedy/laravel-users#37]
**Dear @jeremykenedy , here are the translation files to support the Brazilian Portuguese language, I hope it helps.** 

**Files Translation:**

- app.php
- forms.php
- laravelusers.php
- modals.php

[pt-br.zip](https://github.com/jeremykenedy/laravel-users/files/3045164/pt-br.zip)

**My greetings**
Nicolas dos Reis Barbosa de Oliveira

**Comment by jeremykenedy** [comment]
Thank you!

This has been added to the project in commit https://github.com/jeremykenedy/laravel-users/commit/2d2755402262f41b054feec1c11f4b8298e58155

And is available in 3.3.0
