### ISSUE TITLE
RoleDeniedException

### ISSUE THREAD

**Issue by ffuentese** [jeremykenedy/laravel-users#38]
How do I redirect someone from the admin if they don't have the role "admin" so that they don't see the ugly error? Is there any setting I could modify?

I'm using laravel roles btw.

**Comment by jeremykenedy** [comment]
Hi, If you are using `https://github.com/jeremykenedy/laravel-roles` than there are a couple of options:

1. When the app is in production and debug is set to false they will see a 403 page.
2. You can add a different exception handler: https://github.com/jeremykenedy/laravel-roles#middleware

**Comment by ffuentese** [comment]
Thanks!
