### ISSUE TITLE
Adding role and permission management

### ISSUE THREAD

**Issue by ffuentese** [jeremykenedy/laravel-users#39]
I'm using this package along with laravel-roles and i'd like to be able to manage both users and roles/permissions from this website. Is it already possible or  has anyone else integrated it with role/permission management?

**Comment by jeremykenedy** [comment]
Can you elaborate more on this please?

Are you talking about a GUI/API to add roles and permissions and set up those relationships without a seed?

That is something I have been rolling around in my head for a while for roles packages but I have not had the time. The roles package currently has no GUI or API with it so I have been contemplating doing something like for that package.

**Comment by ffuentese** [comment]
Yeah, basically a GUI that allows us to create/list/update/delete roles, create/list/update/delete permissions and manage them along with what we can already do which is user management. Maybe should I add the same issue in laravel roles?

**Comment by jeremykenedy** [comment]
It's not really an issue, it's more of a feature request. It would be something that would be added to the roles package and extended to this project. Currently, I am not sure when I would have time to create that. 

Thanks,
