### ISSUE TITLE
Method [throwValidationException] does not exist

### ISSUE THREAD

**Issue by titleistfour** [jeremykenedy/laravel-users#4]
Hello,

I'm using the latest version of this package and Laravel 5.5.32.  I'm getting this error when trying to validate creating a new user or editing an existing user.

`Method [throwValidationException] does not exist on [jeremykenedy\laravelusers\App\Http\Controllers\UsersManagementController]`

This is an excellent and very useful package.  It is quite common to need some type of user management.  Thanks for the work on this.

Jay

**Comment by swimlappy** [comment]
I created a [pull request](https://github.com/jeremykenedy/laravel-users/pull/5) to fix this.

Jason

**Comment by jeremykenedy** [comment]
Fixed in PR https://github.com/jeremykenedy/laravel-users/pull/5

Thank you

**Comment by titleistfour** [comment]
This fixed the issue.  Thank you @swimlappy and @jeremykenedy !
