### ISSUE TITLE
Change max password length

### ISSUE THREAD

**Issue by timblanq** [jeremykenedy/laravel-users#40]
How can i change the maximum password length?
A length of 20 characters is not really practical anymore, i think…

Thank you for your great package. 😃

**Comment by jeremykenedy** [comment]
Thank you,

For updating the password that would be right in the controller file located at:

https://github.com/jeremykenedy/laravel-users/blob/master/src/App/Http/Controllers/UsersManagementController.php#L205

To change the default length for creating a laravel account you may need to create a request or directly change the rules in the controller: 
https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Auth/RegisterController.php#L54

Hope that helps,

Thanks,

Jeremy
