### ISSUE TITLE
Select multiple roles

### ISSUE THREAD

**Issue by martijnr17** [jeremykenedy/laravel-users#42]
I use your roles and users package for a lot of laravel website I manage and am missing the multiple roles editor in the users section.
I have some really small changes in your code that enables this to work correctly.
Is it possible to implement this? You only have to change 4 lines of code, see below.

UsersManagementController.php
Line 159 $currentRole    = '';				-> 			$currentRole    = [];
Line 165 $currentRole = $user_role;			->			$currentRole[] = $user_role->id;

edit-user.blade.php
Line 107 <select class="custom-select form-control" name="role" id="role">			->			<select class="custom-select form-control" name="role[]" id="role" multiple>
Line 112 <option value="{{ $role->id }}" {{ $currentRole->id == $role->id ? 'selected="selected"' : '' }}>{{ $role->name }}</option>		->		<option value="{{ $role->id }}" {{ in_array($role->id ,$currentRole) ? 'selected="selected"' : '' }}>{{ $role->name }}</option>

**Comment by jeremykenedy** [comment]
Can you make a PR so I can test it?

**Comment by martijnr17** [comment]
I did my best, its the first time. It are 2 pull requests now, no idea how to make one.
