### ISSUE TITLE
How can I use spatie/laravel-permission?

### ISSUE THREAD

**Issue by bnymn** [jeremykenedy/laravel-users#45]
Hello there,

I have read the following statement in your README file.
> Laravel users can work out the box with or without the following roles packages:

I don't think it is true. I have installed **spatie/laravel-permission** package, but it does not seem to be working with your package.

For example, I tried to change user permission, but I got an exception saying that **detachAllRoles()** does not exist in User class.

**Comment by jeremykenedy** [comment]
Should work. Use laravel-roles package.

**Comment by bnymn** [comment]
Hi @jeremykenedy ,

I think your documentation is misleading. It does not work out-of-the-box with other permission packages. This package has a strong connection with laravel-roles package. You might consider updating the documentation.

**Comment by jeremykenedy** [comment]
It does work out the box with others, they just changed their methods recently and it may need to be adjusted accordingly.

**Comment by karneaud** [comment]
> It does work out the box with others, they just changed their methods recently and it may need to be adjusted accordingly.

What version does it work with? 
Any recommendations?
