### ISSUE TITLE
Issue with routes prefixes and middlewares

### ISSUE THREAD

**Issue by IsmaHaro** [jeremykenedy/laravel-users#46]
So my system works but with an admin section, this admin section has the prefix /admin on the routes, so my main routes go for example on /admin/something

In this case 
1) I can't go the /admin/users instead I have to go on /users, how can I change this?
2) I need to assign special middlewares so that only certain roles can go to /admin/users, how can I do this?

Thanks!

**Comment by jeremykenedy** [comment]
You cannot change the routes. 

You set the middleware in the end or config file as outlined in the readme.

**Comment by karneaud** [comment]
Why can't the roles be changed...it makes sense to have them at "admin/user/create" and atleast have them override any existing. Or at least given the opportunity to overide them
