### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by m-rufflesmcghie** [jeremykenedy/laravel-users#47]
Awesome work with this package and also the roles package. 
Am slightly confused re Users.... 
When running the vendor publish command this does not push config.
Do I need to copy this manually into config directory? Roles seemed to do it automatically. 
Just getting use to laravel n will definitely contribute to getting users & roles packages working together via GUI as I've seen a few pull requests already.

**Comment by jeremykenedy** [comment]
It published as outline here:

https://github.com/jeremykenedy/laravel-users/blob/master/src/LaravelUsersServiceProvider.php#L56

Try using the —force flag.
