### ISSUE TITLE
Soft delete on users

### ISSUE THREAD

**Issue by felixpenrose** [jeremykenedy/laravel-users#49]
Is there a date in mind to implement soft deletes on the user model? I see it's on the road map from the config file.

I'm currently setting the trait on my User model, so that does at least give an interim solution, but it'd be great to have this built into the interface.

**Comment by jeremykenedy** [comment]
At this time I do not know but I will try and add it within the next couple of months.

I want to do so in way to make it completely optional so it will not have a breaking change for current package users but will allow them to add it on update and new installation as an option.

Thank you :)
