### ISSUE TITLE
Allow adding a custom middleware to all routes

### ISSUE THREAD

**Issue by pjotrsavitski** [jeremykenedy/laravel-users#52]
Would it be possible to add a custom middleware to protect the routes?

The solution might be needed to protect the user related routes in case one does not install the roles and permissions module. There is case where it is not needed and admin is determined based on the users table itself. No other roles are really needed.

The perfect scenario would be to just add the a configuration or even two and to trigger it within `__constuct()` method of the controller. It could be similar to how roles middleware is checked and triggered, just that it would allow one to configure any middleware to be enforced.

There did not seem to be a convenient way to make changes to an already defined routes.

**Comment by jeremykenedy** [comment]
It outlines this in the readme. In the env

https://github.com/jeremykenedy/laravel-users#configuration

**Comment by pjotrsavitski** [comment]
Sorry to be bothering, but configuration allows to enable `auth` middleware and `rolesMiddleware`, but the second one will only run in case `rolesEnabled` is set to **true** as the code states:
https://github.com/jeremykenedy/laravel-users/blob/master/src/App/Http/Controllers/UsersManagementController.php#L34

This means that templates would also rely on checking for the roles to be present and fail as the roles module would not be there.

Removing the check for `rolesEnabled` would do the trick and run any custom middleware defined, though that would not really have anything to do with roles (might not have as the middleware could be anything).

**Comment by PaulMcRoar** [comment]
I have to agree with @pjotrsavitski  , I have another 2fa middleware I've plugged into my project and need to add this to all routes (I'm not using laravelroles).  I'm going to have to fork the project and enable extra middleware to be configured in.
