### ISSUE TITLE
Edit URL assumed as base_url

### ISSUE THREAD

**Issue by terrorfall** [jeremykenedy/laravel-users#58]
This line on show-user.blade.php 

`<a href="/users/{{$user->id}}/edit" class="btn btn-block btn-md btn-warning">`

Assumes that the Laravel app is not served from a subfolder and should be changed to

`<a href="{{ url('/') }}/users/{{$user->id}}/edit" class="btn btn-block btn-md btn-warning">`

**Comment by jeremykenedy** [comment]
Why would it not serve from root? The routes are all based off the root. If you trying to change the routes it will not work.

https://github.com/jeremykenedy/laravel-users#routes-in-depth

**Comment by terrorfall** [comment]
You're correct, this was a bad config setup on my part
