### ISSUE TITLE
[i18n] Untranslatable strings

### ISSUE THREAD

**Issue by bbalet** [jeremykenedy/laravel-users#68]
In 
https://github.com/jeremykenedy/laravel-users/blob/d76af3b120961dd0d321f09f80a498f5b3466df6/src/resources/views/partials/form-status.blade.php#L25
And
https://github.com/jeremykenedy/laravel-users/blob/d76af3b120961dd0d321f09f80a498f5b3466df6/src/resources/views/partials/form-status.blade.php#L40

Strings are hard coded. Please fix so I can PR fr language support

**Comment by jeremykenedy** [comment]
You can also fix that in a PR
