### ISSUE TITLE
Error Class name must be a valid object or a string

### ISSUE THREAD

**Issue by titia-sudo** [jeremykenedy/laravel-users#70]
Hi!
I integrated the user management module into my project. The problem is that when I try to access it I get this error that displays:
 
![error](https://user-images.githubusercontent.com/67266974/85290172-17702980-b488-11ea-82c6-7d3b71e6988b.png)

thanks you

**Comment by jeremykenedy** [comment]
You  Are not using it correctly and your environment is t configured correctly m as well as your setup of your project is wrong as evidenced by serving the the wrong pathed folder.

**Comment by titia-sudo** [comment]
Hello, thank you for your answer!
I've been trying to follow the procedure you gave. From the root folder of
your projects I first execute:
*composer require jeremykenedy / laravel-users*
then:
*php artisan vendor: publish --tag = laravelusers.*
if i made a mistake or if i skip a step, please guide me. Thank you

Le lun. 22 juin 2020 à 13:58, Jeremy Kenedy <notifications@github.com> a
écrit :

**Comment by jeremykenedy** [comment]
Did you do all the steps exactly

**Comment by titia-sudo** [comment]
Yes! Help me because it's been several days that I am on this problem

Le mer. 24 juin 2020 à 07:52, Jeremy Kenedy <notifications@github.com> a
écrit :

**Comment by ettr** [comment]
I am facing the same issue on my laravel project.
What I did:
composer require jeremykenedy/laravel-users
php artisan vendor:publish --tag=laravelusers
php artisan migrate
php artisan serve

I do not have any new controllers in /app/Http/Controllers but vendor/jeremykenedy/laravel-users/src/App/Http/Controllers/UsersManagementController.php exists and throws the same error "Class name must be a valid object or a string " on line 52

config/laravelusers.php has an entry:
'defaultUserModel'              => 'App\User',

My user model is specified in exaktly that file.

**Comment by jeremykenedy** [comment]
I just installed the package on a fresh Laravel install and it worked perfectly. I cannot duplicate the issue.

**Comment by ettr** [comment]
Strange. When I manually type in \App\User instead of config('laravelusers.defaultUserModel') it works.
Should php artisan vendor:publish --tag=laravelusers normally publish the controller as well? In my case it only publishes the views, the config and the translation files.

I am on Laravel 7.21.0

**Comment by jeremykenedy** [comment]
Your config may be reading from a cached file in which the variable/config file doesn't exists.

try clearing your cache.

```
php artisan cache:clear
```

**Comment by ettr** [comment]
I cleared the cache but still the same issue.
App.User is the wrong path from vendor/jeremykenedy/laravel-users/src/App/Http/Controllers/UsersManagementController.php as a starting point...

**Comment by jeremykenedy** [comment]
I cannot replicate

**Comment by ettr** [comment]
`php artisan config:clear`
and
`'defaultUserModel'              => '\App\User',`
did the trick!
