### ISSUE TITLE
[bug] Can't edit user e-mail address

### ISSUE THREAD

**Issue by robertvanlienden** [jeremykenedy/laravel-users#73]
Fount some bug where I can't edit the user e-mail address.

**Got there error; The email may only contain letters, numbers, dashes and underscores.**

Seems right the wrong validation is in here.

Right now I don't have the priority and time to fix this, so decided to put in some bug report.

See my loom screenshare below;
https://www.loom.com/share/1264179cddb046028ecd0f351c2789e6

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-users#opening-an-issue
