### ISSUE TITLE
Custom Users Model (not being honored?)

### ISSUE THREAD

**Issue by RomanoCodes** [jeremykenedy/laravel-users#76]
I am using a user model with a custom table named defined:
![image](https://user-images.githubusercontent.com/1924944/106667473-d1bb2980-655d-11eb-8cdd-2aab78abc81e.png)

However when doing something like adding a new user, an error is thrown. The error seems to be spitting back the '.users' table which makes me think some kind of default is not being overridden. Is this the case? How can I fix this (while keeping my custom user table)?

Thanks!

**Comment by jeremykenedy** [comment]
The users table is not defined in this package it all funs off the config file var:

https://github.com/jeremykenedy/laravel-users/blob/master/src/config/laravelusers.php#L39

Which is used in:

https://github.com/jeremykenedy/laravel-users/blob/master/src/App/Http/Controllers/UsersManagementController.php

by calling `config('laravelusers.defaultUserModel')`.

You may need to clear composer and the config of your app.

**Comment by RomanoCodes** [comment]
Despite clearing all forms of cache and even bouncing my apache server, I am still getting the following:
![image](https://user-images.githubusercontent.com/1924944/106682118-ae50a880-6576-11eb-85e2-9dd00ce0a63b.png)

Mind you, I have also specified the specific user model in the config file. I am at a loss.

**Comment by jeremykenedy** [comment]
What line does it say it fails on with that stack trace in the laravel.log

**Comment by jeremykenedy** [comment]
This issue is in the controller rules I believe.

I am not sure when I will have time to fix it but its the rules I think in these lines:

* https://github.com/jeremykenedy/laravel-users/blob/master/src/App/Http/Controllers/UsersManagementController.php#L94
* https://github.com/jeremykenedy/laravel-users/blob/master/src/App/Http/Controllers/UsersManagementController.php#L95
* https://github.com/jeremykenedy/laravel-users/blob/master/src/App/Http/Controllers/UsersManagementController.php#L203

The issue is it calling the `unique:users` on those lines.

**Comment by RomanoCodes** [comment]
I'm handed a bunch of things... I'm not sure if this will be helpful:
![image](https://user-images.githubusercontent.com/1924944/106683027-937f3380-6578-11eb-9bcd-8251d510d8b2.png)

![image](https://user-images.githubusercontent.com/1924944/106683050-9f6af580-6578-11eb-8aaf-0c6088fbb7bc.png)

Oddly, in the debug pane, it shows a query that seems correct:
![image](https://user-images.githubusercontent.com/1924944/106683195-eb1d9f00-6578-11eb-9b5a-a749f80d9027.png)

**Comment by RomanoCodes** [comment]
You're right... I did some see some validator flags get raised. Thanks for maybe confirming that being the case... I can try to sidestep that and see what happens (when I have a moment later tonight). Will keep you posted.

**Comment by RomanoCodes** [comment]
Great success. Stripping out the `|unique:users` solved the issue.

Thanks for your help on this (and of course all the other work you've done)!
