### ISSUE TITLE
Support Laravel 10 and remove abandoned dependency

### ISSUE THREAD

**Issue by cameronjohnson-mz** [jeremykenedy/laravel-users#84]
Can this package get updated to support Laravel 10 and remove the `laravecollective/html` dependency because it's abandoned?
The replace package is `spatie/laravel-html`.

Issue:
jeremykenedy/laravel-users v4.3.0 requires laravelcollective/html (^5.4|^5.5|^5.6|^5.7|^5.8|^6.0|^7.0|^8.0)
Package laravelcollective/html is abandoned, you should avoid using it. Use spatie/laravel-html instead.

**Comment by jeremykenedy** [comment]
It seems to work fine on other projects that use this with Laravel 10
