### ISSUE TITLE
appJsPublicFile value suggestion for Laravel 9 \ Vite

### ISSUE THREAD

**Issue by cameronjohnson-mz** [jeremykenedy/laravel-users#85]
This appears to be working with Laravel 9, but do you have any suggestions what that value should for `appjsPublicFile` and `appcssPublicFile` since we should be using Laravel Vite instead of Laravel Mix going forward?

My CSS and JS files are bundled here now:

<repo>/public/build/assets/app-238453fd.css
<repo>/public/build/assets/app-d35ea772.js
 
```
    'enableAppCss'                  => true,
    'appCssPublicFile'              => 'css/app.css',

    'enableBootstrapJsCdn'          => true,
    'bootstrapJsCdn'                => 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js',

    'enableAppJs'                   => true,
    'appJsPublicFile'               => 'js/app.js',
```

Also, composer says this dependency `laravelcollective/html` is abandoned and should avoid using it. They suggest using `spatie/laravel-html` instead.

Can this be updated too?

**Comment by jeremykenedy** [comment]
I accept PR's.

Thank you
